test:
  workers:
    type: local
    number: 5
  rounds:
    - label: query_readwrite_1090
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 3000
      workload:
        module: benchmarks/samples/fabric/marbles/query_readwrite_1090.js
